client:
    resource: "@ClientBundle/Controller/"
    type:     annotation
    prefix:   /

user:
    resource: "@UserBundle/Controller/"
    type:     annotation
    prefix:   /

admin:
    resource: "@AdminBundle/Controller/"
    type:     annotation
    prefix:   /admin

login:
    path: /login
    defaults:
        _controller: UserBundle:Security:login

login_check:
    path: /login_check

logout:
    path: /logout

