security:
  encoders:
    Symfony\Component\Security\Core\User\User: plaintext
    UserBundle\Entity\User: plaintext

  role_hierarchy:
    ROLE_ADMIN:       ROLE_USER
    ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

  providers:
    main:
      entity:
        class:    UserBundle\Entity\User
        property: username

  firewalls:
    dev:
      pattern: ^/(_(profiler|wdt)|css|images|js)/
      security: false
    main:
#        main est le nom du pare feu
      pattern:   ^/
#      pattern: ^/ est un masque d'URL. Cela signifie que toutes les URL commençant par
#« / » (c'est-à-dire notre site tout entier) sont protégées par ce pare-feu
      anonymous: true
#anonymous: true accepte les utilisateurs anonymes. 
#Nous protégerons nos ressources grâce aux rôles.
      provider:     main
#provider: in_memory est le fournisseur d'utilisateurs pour ce pare-feu. 
#un pare-feu a besoin de savoir où trouver ses utilisateurs, cela se fait par le biais 
#de ce paramètre. in_memory correspond au nom du fournisseur défini dans la section 
#providers
      form_login:
          default_target_path: /admin
          login_path: login
          check_path: login_check
          
          
      logout:
        path:       logout
        target:     /
          
  access_control:
      - { path: ^/, roles: IS_AUTHENTICATED_ANONYMOUSLY }
      - { path: ^/admin, roles: ROLE_USER}
      - { path: ^/superadmin, roles: ROLE_ADMIN}
#      On sécurise toutes les Url qui commencent par /admin.